[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 4
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
arbitrum = "${ARB_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
